CREATE TABLE clients (
    id SERIAL4 PRIMARY KEY,
  name VARCHAR(600) NOT NULL,
  img_url TEXT,
  children VARCHAR(600) NOT NULL,
  host BOOLEAN NOT NULL
);

CREATE TABLE carers (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(600) NOT NULL,
  img_url TEXT NOT NULL,
  age INTEGER NOT NULL
);

CREATE TABLE locations (
  id SERIAL4 PRIMARY KEY,
  street_address VARCHAR(1000) NOT NULL,
  suburb VARCHAR(400) NOT NULL,
  city VARCHAR(400) NOT NULL,
  host BOOLEAN NOT NULL
);
